export const MONTHS = [
  { id: 1, value: 'adorable', name: 'January' },
  { id: 2, value: 'flirting', name: 'February' },
  { id: 3, value: 'cute', name: 'March' },
  { id: 4, value: 'confused', name: 'April' },
  { id: 5, value: 'excited', name: 'May' },
  { id: 6, value: 'baby', name: 'June' },
  { id: 7, value: 'itchy', name: 'July' },
  { id: 8, value: 'fail', name: 'August' },
  { id: 9, value: 'sleepy', name: 'September' },
  { id: 10, value: 'adorable', name: 'October' },
  { id: 11, value: 'cute', name: 'November' },
  { id: 12, value: 'excited', name: 'December' }
];

export const DAYS = [
  { id: 1, value: 'panda', name: 1 },
  { id: 2, value: 'dog', name: 2 },
  { id: 3, value: 'cat', name: 3 },
  { id: 4, value: 'koala', name: 4 },
  { id: 5, value: 'duck', name: 5 },
  { id: 6, value: 'panda', name: 6 },
  { id: 7, value: 'dog', name: 7 },
  { id: 8, value: 'cat', name: 8 },
  { id: 9, value: 'koala', name: 9 },
  { id: 10, value: 'duck', name: 10 },
  { id: 11, value: 'panda', name: 11 },
  { id: 12, value: 'dog', name: 12 },
  { id: 13, value: 'cat', name: 13 },
  { id: 14, value: 'koala', name: 14 },
  { id: 15, value: 'duck', name: 15 },
  { id: 16, value: 'panda', name: 16 },
  { id: 17, value: 'dog', name: 17 },
  { id: 18, value: 'cat', name: 18 },
  { id: 19, value: 'koala', name: 19 },
  { id: 20, value: 'duck', name: 20 },
  { id: 21, value: 'panda', name: 21 },
  { id: 22, value: 'dog', name: 22 },
  { id: 23, value: 'cat', name: 23 },
  { id: 24, value: 'koala', name: 24 },
  { id: 25, value: 'duck', name: 25 },
  { id: 26, value: 'panda', name: 26 },
  { id: 27, value: 'dog', name: 27 },
  { id: 28, value: 'cat', name: 28 },
  { id: 29, value: 'koala', name: 29 },
  { id: 30, value: 'duck', name: 30 },
  { id: 31, value: 'hedgehog', name: 31 }
];
